config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'businesses#index'

  resources :businesses, only: [:show]
  resources :pages, param: :slug, only: [:show]
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  devise :confirmable, :database_authenticatable, :lockable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
# frozen_string_literal: true

class Business < ApplicationRecord
  validates :name, presence: true

  has_many :business_delivery_areas, dependent: :destroy
  has_many :delivery_areas, through: :business_delivery_areas
  has_many :opening_hours, dependent: :destroy

  accepts_nested_attributes_for :opening_hours, allow_destroy: true

  def opening_hours_to_show
    opening_hours.group_by(&:day_as_string).map do |day_as_string, opening_hours|
      opening_hours.map! do |opening_hour|
        opening_hour.opening_time.strftime('%H:%M') + ' - ' + opening_hour.closing_time.strftime('%H:%M')
      end
      [day_as_string, opening_hours.to_sentence]
    end
  end
end

app/models/business_delivery_area.rb
# frozen_string_literal: true

class BusinessDeliveryArea < ApplicationRecord
  belongs_to :business
  belongs_to :delivery_area
end

app/models/delivery_area.rb
# frozen_string_literal: true

class DeliveryArea < ApplicationRecord
  validates :name, presence: true
  validates :postcode, presence: true,
                       length: { is: 5 },
                       format: { with: /\A\d+x*\z/,
                                 message: 'only digits or x at the end' }

  has_many :business, through: :business_delivery_areas
  has_many :business_delivery_areas, dependent: :destroy

  def self.as_form_collection
    order(:postcode).map { |da| ["#{da.postcode} - #{da.name}", da.id] }
  end
end

app/models/opening_hour.rb
# frozen_string_literal: true

class OpeningHour < ApplicationRecord
  belongs_to :business

  validates :day, presence: true,
                  numericality: { only_integer: true,
                                  greater_than_or_equal_to: 0,
                                  less_than_or_equal_to: 6 }
  validates :opening_time, :closing_time, presence: true

  default_scope { order(day: :asc, opening_time: :asc) }

  def self.days_as_form_collection
    [
      ['Sunday', 0],
      ['Monday', 1],
      ['Tuesday', 2],
      ['Wednesday', 3],
      ['Thursday', 4],
      ['Friday', 5],
      ['Saturday', 6]
    ]
  end

  def day_as_string
    %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday][day]
  end
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :slug, presence: true, uniqueness: true
  validates :menu_order, numericality: { only_integer: true }, allow_nil: true
  validates :title, presence: true

  scope :for_menu, -> { where.not(menu_order: nil).order(:menu_order) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/businesses_controller.rb
# frozen_string_literal: true

class BusinessesController < ApplicationController
  def index; end

  def show; end

  private

  def business
    @business ||= Business.find(params[:id])
  end
  helper_method :business

  def businesses
    @businesses ||= Business.order('RANDOM()')
  end
  helper_method :businesses
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def show; end

  private

  def page
    @page ||= Page.find_by(slug: params[:slug])
  end
  helper_method :page
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/businesses/index.erb
<div class="card-columns">
  <% businesses.each do |business| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to business.name, business_path(business) %></h5>
        <p class="card-text">
          <span class="badge badge-light"><%= business.business_type %></span>
          <span class="badge badge-light"><%= business.business_sub_type %></span>
        </p>
        <p class="card-text"><%= simple_format(truncate(business.description, length: 500, separator: ' ') { link_to(' (see more)', business_path(business)) }) %></p>
        <%= link_to 'View details', business_path(business), class: 'btn btn-primary' %>
        <% if business.website.present? %>
          <a href="<%= business.website %>" target="_blank" class="btn btn-light">Website</a>
        <% end %>
        <% if business.order_url.present? %>
          <a href="<%= business.order_url %>" target="_blank" class="btn btn-light">Order</a>
        <% end %>
        <% if business.phone.present? %>
          <a href="tel:<%= business.phone %>" target="_blank" class="card-link">
            <svg class="bi bi-phone" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M11 1H5a1 1 0 00-1 1v12a1 1 0 001 1h6a1 1 0 001-1V2a1 1 0 00-1-1zM5 0a2 2 0 00-2 2v12a2 2 0 002 2h6a2 2 0 002-2V2a2 2 0 00-2-2H5z" clip-rule="evenodd"/>
              <path fill-rule="evenodd" d="M8 14a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"/>
            </svg>
            <small><%= business.phone %></small>
          </a>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/businesses/show.erb
<%= link_to '<< Back', :back, class: 'btn btn-link' %>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= business.name %></h5>
    <p class="card-text">
      <span class="badge badge-light"><%= business.business_type %></span>
      <span class="badge badge-light"><%= business.business_sub_type %></span>
    </p>
    <p class="card-text"><%= simple_format business.description %></p>
    <% if business.website.present? %>
      <a href="<%= business.website %>" target="_blank" class="btn btn-light">Website</a>
    <% end %>
    <% if business.order_url.present? %>
      <a href="<%= business.order_url %>" target="_blank" class="btn btn-light">Order</a>
    <% end %>
    <% if business.phone.present? %>
      <a href="tel:<%= business.phone %>" target="_blank" class="card-link">
        <svg class="bi bi-phone" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M11 1H5a1 1 0 00-1 1v12a1 1 0 001 1h6a1 1 0 001-1V2a1 1 0 00-1-1zM5 0a2 2 0 00-2 2v12a2 2 0 002 2h6a2 2 0 002-2V2a2 2 0 00-2-2H5z" clip-rule="evenodd"/>
          <path fill-rule="evenodd" d="M8 14a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"/>
        </svg>
        <small><%= business.phone %></small>
      </a>
    <% end %>
  </div>
  <% if business.opening_hours.any? %>
    <div class="card-body">
      <h6 class="card-title">Opening hours</h6>
      <table class="table table-borderless table-sm w-auto">
        <tbody>
          <% business.opening_hours_to_show.each do |day_as_string, opening_hours| %>
            <tr>
              <th><%= day_as_string %></th>
              <td><%= opening_hours %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  <% if business.delivery_areas.any? %>
    <div class="card-body">
      <h6 class="card-title">Delivery areas</h6>
      <ul>
        <% business.delivery_areas.each do |delivery_area| %>
          <li><%= delivery_area.postcode %> - <%= delivery_area.name %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162152041-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-162152041-1');
      </script>
    <% end %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Stay Home Berlin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Stay Home Berlin</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <% Page.for_menu.each do |page| %>
            <li class="nav-item">
              <%= link_to page.title, page_path(page.slug), class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div id="main-container" class="container container-md">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/show.erb
<h1><%= page.title %></h1>
<%= simple_format page.content %>